### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by Amazingren** [yf1019/CT-Net#1]
Hi @yf1019 ,
Thanks for your really interesting work, could I know when will you update the code for CT-Net? Hoping this will be soon!
Many thanks

**Comment by yf1019** [comment]
Hi, Sorry for the delay. I'm very busy recently and I'll try to release the code at the end of this month.

**Comment by Amazingren** [comment]
> Hi, Sorry for the delay. I'm very busy recently and I'll try to release the code at the end of this month.

It's nice to hear from you. Hoping this will not bring you inconvenience.
