### ISSUE TITLE
Running model on random image

### ISSUE THREAD

**Issue by srch07** [yf1019/CT-Net#2]
@yf1019 The code seems to have one to one mapping of deepfashion image to pose file.
Can it be run on random single image pair without pose file provided?

Because whole point of using openpose would be to predict the pose from any given image, right?

**Comment by yf1019** [comment]
Hi, our model depends on several pretrained model to extract the low-level information of the human, including human keypoints, densepose descriptor and the body parsing. 

For the efficiency of testing and training, we prepare these inputs first, just as the one mapping of deepfashion image to pose file. But our model is able to run on any random image pairs. To achieve this, you may cascade our model with the pretrained model and finetune the whole framework.

**Comment by srch07** [comment]
@yf1019 Thanks for replying. Makes complete sense.
It will be great if you can guide me how can I generate those for my own dataset, because looking at individual pretrained models, their output seems to differ in format compared to how it has been used in this model.
